src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 * @UniqueEntity(fields={"libelle"})
 */
class Categorie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $libelle;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="categories")
     */
    private $CategorieParente;

    /**
     * @ORM\OneToMany(targetEntity=Categorie::class, mappedBy="CategorieParente")
     */
    private $categories;

    /**
     * @ORM\Column(type="boolean")
     */
    private $valid;

    /**
     * @ORM\Column(type="boolean")
     */
    private $deleted;

    /**
     * @ORM\ManyToMany(targetEntity=BlogPost::class, mappedBy="categories")
     */
    private $blogPosts;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->blogPosts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getCategorieParente(): ?self
    {
        return $this->CategorieParente;
    }

    public function setCategorieParente(?self $CategorieParente): self
    {
        $this->CategorieParente = $CategorieParente;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setCategorieParente($this);
        }

        return $this;
    }

    public function removeCategory(self $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getCategorieParente() === $this) {
                $category->setCategorieParente(null);
            }
        }

        return $this;
    }

    public function getValid(): ?bool
    {
        return $this->valid;
    }

    public function setValid(bool $valid): self
    {
        $this->valid = $valid;

        return $this;
    }

    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }

    /**
     * @return Collection|BlogPost[]
     */
    public function getBlogPosts(): Collection
    {
        return $this->blogPosts;
    }

    public function addBlogPost(BlogPost $blogPost): self
    {
        if (!$this->blogPosts->contains($blogPost)) {
            $this->blogPosts[] = $blogPost;
            $blogPost->addCategory($this);
        }

        return $this;
    }

    public function removeBlogPost(BlogPost $blogPost): self
    {
        if ($this->blogPosts->contains($blogPost)) {
            $this->blogPosts->removeElement($blogPost);
            $blogPost->removeCategory($this);
        }

        return $this;
    }


}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="services")
     */
    private $user;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isValid;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsValid(): ?bool
    {
        return $this->isValid;
    }

    public function setIsValid(?bool $isValid): self
    {
        $this->isValid = $isValid;

        return $this;
    }
    public function isValid(): ?bool
    {
        return $this->isValid;
    }
}

src/Form/AssociationType.php
<?php

namespace App\Form;

use App\Entity\Association;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class AssociationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('UserA')
            ->add('titre')
            ->add('siege')
            ->add('but')
            ->add('logo', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '5120k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image file',
                    ])
                ],
            ])
            ->add('adresse')
            ->add('nombreMembre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Association::class,
        ]);
    }
}

src/Controller/AssociationController.php
<?php

namespace App\Controller;
use App\Form\AssociationAjoutInfoType;
use App\Form\AssociationEditFormType;
use App\Form\AssociationEditPAFormType;
use App\Repository\ActualiteRepository;
use App\Repository\EvenementRepository;
use App\Repository\OpportuniteRepository;
use App\Services\UploadHelper;

use App\Entity\Association;
use App\Form\AssociationType;
use App\Repository\AssociationRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use MongoDB\BSON\Type;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/association")
 */
class AssociationController extends AbstractController
{

private $associationRepository;
private $entityManager;
    /**
     * @var UploadHelper
     */
    private $uploadHelper;
    public function __construct(AssociationRepository $associationRepository, UploadHelper $uploadHelper ,EntityManagerInterface $entityManager)
    {
       $this->associationRepository=$associationRepository;
        $this->entityManager = $entityManager;
        $this->uploadHelper = $uploadHelper;

    }

    /**
     * @Route("/", name="association_index", methods={"GET"})


     */
    public function index(AssociationRepository $associationRepository): Response
    {  $associations=$this->associationRepository->findAll();
//        return $this->render("proprietaireAssociation/asoociation/associationform.html.twig", ['associationform'=>$form->createView(),

        return $this->render('admin/association/association.html.twig', [
            'associations' => $associationRepository->findAll(),
        ]);
    }

//    /**
//     * @Route("/new", name="association_new", methods={"GET","POST"})
//     */
//    public function new(Request $request): Response
//    {
//        $association = new Association();
//        $form = $this->createForm(AssociationType::class, $association);
//
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $entityManager = $this->getDoctrine()->getManager();
//            $entityManager->persist($association);
//            $entityManager->flush();
//
//            return $this->redirectToRoute('association_index');
//        }
//
//        return $this->render('association/new.html.twig', [
//            'association' => $association,
//            'form' => $form->createView(),
//        ]);
//    }


    /**
     * @Route("/new", name="association_new", methods={"GET","POST"})
     */
    public function new(AssociationRepository $associationRepository,Request $request,EntityManagerInterface $manager): Response
    {
        $association = new Association();
        $form = $this->createFormBuilder($association);

        $form=$this->createFormBuilder($association)
            ->add('UserA',null,['label'=>'Choisissez le proprietaire '])

            ->add('titre',
                TextType::class, [
                    'required' => true,
                    'label' => "Entrez le nom d'association",
                    'attr' => ['class' => 'form-control']
                ])
            ->add('siege',
                TextType::class, [
                    'required' => true,
                    'label' => "Entrez le siege d'association",
                    'attr' => ['class' => 'form-control']
                ])
            ->add('adresse',
                TextType::class, [
                    'required' => true,
                    'label' => "Entrez l'adresse d'association",
                    'attr' => ['class' => 'form-control']
                ])
            ->add('nombreMembre',
                TextType::class, [
                    'required' => true,
                    'label' => "Entrez le nombre des membres d'association",
                    'attr' => ['class' => 'form-control']
                ])
            ->add('logo',FileType::class,['label'=>'Charger le logo d\'association' ])
            ->add('but', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'rows' => "9",
                    'cols' => "45"
                ],
                'label' => "Entrez le but d'association "
            ])
            ->getForm();
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $file=$form->get('logo')->getData();
            $fileName=md5(uniqid()).'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $association->setLogo($fileName);
            $association=$form->getData();
            $association->setValid(true);
            $association->setDeleted(false);

//            $entityManager = $this->getDoctrine()->getManager();
            $manager->persist($association);
            $manager->flush();
            $this->addFlash('success', 'Association  bien été enregistrée.');

            return $this->redirectToRoute('association_index');
        }

        return $this->render("admin/association/associationform.html.twig", ['associationform'=>$form->createView(),
            'associations' => $associationRepository->findAll(),
            'form' => $form->createView(),

        ]);
    }











//    /**
//     * @Route("/{id}", name="association_show", methods={"GET"})
//     */
//    public function show(Association $association): Response
//    {
//        return $this->render('association/show.html.twig', [
//            'association' => $association,
//        ]);
//    }

    /**
     * @Route("/{id}/edit", name="association_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AssociationRepository $associationRepository,AssociationEditFormType $associationEditFormType,Association $association): Response
    {
        $form = $this->createForm(AssociationEditFormType::class, $association);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file=$form->get('logo')->getData();
            $fileName=md5(uniqid()).'.'.$file->guessExtension();

            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $association->setLogo($fileName);



$this->entityManager->persist($association);
            $this->entityManager->flush();
            $this->addFlash("success","Association modifiée");

            return $this->redirectToRoute('association_index');
        }

        return $this->render("admin/association/associationform.html.twig", ['associationform'=>$form->createView(),
            'associations' => $associationRepository->findAll(),
            'form' => $form->createView(),

        ]);
    }

    /**
     * @Route("/{id}", name="association_delete", methods={"POST"})
     */
    public function delete(Request $request, Association $association): Response
    {
        if ($this->isCsrfTokenValid('delete'.$association->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($association);
            $entityManager->flush();
        }

        return $this->redirectToRoute('association_index');

    }

///**
// * @Route("/ass/{idPA}",name="newAss")
// * @IsGranted("ROLE_SUPERUSER")
// */
//public function creerAss (AssociationRepository $associationRepository,SluggerInterface $slugger,$idPA,Request $requete,UserRepository $DirecteurRepository, EntityManagerInterface $manager){
//    $ass=new Association();
////    $ass->setCreatedAt(new \DateTime('now'))  ;
//    $directeur=$DirecteurRepository->find($idPA);
////        dd($directeur);
//    $form=$this->createFormBuilder($ass)
//->add('UserA'
//)
//
//        ->add('titre',
//            TextType::class, [
//                'required' => true,
//                'label' => "Entrez le nom de votre association",
//                'attr' => ['class' => 'form-control']
//            ])
//        ->add('adresse',
//            TextType::class, [
//                'required' => true,
//                'label' => "Entrez l\'adresse de votre association",
//                'attr' => ['class' => 'form-control']
//            ])
//        ->add('nombreMembre',
//            TextType::class, [
//                'required' => true,
//                'label' => "Entrez le nombre des membres de votre association",
//                'attr' => ['class' => 'form-control']
//            ])
//        ->add('logo',FileType::class,['label'=>'Charger votre logo d\'association' ])
//        ->add('but', TextareaType::class, [
//            'attr' => [
//                'class' => 'form-control',
//                'rows' => "9",
//                'cols' => "45"
//            ],
//            'label' => "Entrez le but de votre assocition "
//        ])

templates/association/_delete_form.html.twig
<form method="post" action="{{ path('association_delete', {'id': association.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ association.id) }}">
    <button class="btn">Delete</button>
</form>

templates/association/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/association/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Association{% endblock %}

{% block body %}
    <h1>Edit Association</h1>

    {{ include('association/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('association_index') }}">back to list</a>

    {{ include('association/_delete_form.html.twig') }}
{% endblock %}

templates/association/index.html.twig
{#{% extends "admin/bars.html.twig" %}#}

{#{% block title %}Association index{% endblock %}#}

{#{% block body %}#}
{#    <h1>Association index</h1>#}

{#    <table class="table">#}
{#        <thead>#}
{#            <tr>#}
{#                <th>Id</th>#}
{#                <th>Titre</th>#}
{#                <th>Siege</th>#}
{#                <th>But</th>#}
{#                <th>Logo</th>#}
{#                <th>Adresse</th>#}
{#                <th>NombreMembre</th>#}
{#                <th>actions</th>#}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#        {% for association in associations %}#}
{#            <tr>#}
{#                <td>{{ association.id }}</td>#}
{#                <td>{{ association.titre }}</td>#}
{#                <td>{{ association.siege }}</td>#}
{#                <td>{{ association.but }}</td>#}
{#             <td>   <img width="50px" height="50px" src=" {{ asset('uploads/images/'  ~ association.logo) }}" alt="Awesome Image">#}
{#             </td>#}
{#                <td>{{ association.logo }}</td>#}
{#                <td>{{ association.adresse }}</td>#}
{#                <td>{{ association.nombreMembre }}</td>#}
{#                <td>#}
{#                    <a href="{{ path('association_show', {'id': association.id}) }}">show</a>#}
{#                    <a href="{{ path('association_edit', {'id': association.id}) }}">edit</a>#}
{#                </td>#}
{#            </tr>#}
{#        {% else %}#}
{#            <tr>#}
{#                <td colspan="8">no records found</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#        </tbody>#}
{#    </table>#}

{#    <a href="{{ path('newAss',{'idPA':app.user.id}) }}">Create new</a>#}
{#{% endblock %}#}
{% extends "admin/bars.html.twig" %}

{% block contenpage %}
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h5> Listing </h5>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Liste des associations</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="{{ path('newAss',{'idPA':app.user.id}) }}" class="btn btn-success">NEW</a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <form action="{{ path('groupaction_association') }}" id="grpaction" method="post" name="grpaction">
                                <div class="form-group form-inline">
                                    <select class="form-control" name="action" required id="action_select">
                                        <option value="">Action de groupe</option>
                                        <option value="desactiver">Desactiver</option>
                                        <option value="activer">Activer</option>
                                        <option value="supprimer">Supprimer</option>
                                    </select>
                                    <button class="btn btn-primary" type="submit">Go!!</button>
                                </div>

                            </form>
                            <table id="example" class="display table table-striped table-bordered dataminetables" >
                                <thead>
                                <th><input type="checkbox" id="select_all" name="select_all"></th>
                                <th>Titre</th>
                                <th>Siege</th>
                                <th>But</th>
                                <th>logo</th>
                                <th>Adresse</th>
                                <th>Nombre des membres</th>



                                <th>Modifier</th>
                                <th>Etat ?</th>
                                <th>Suprimer</th>
                                </thead>
                                <tbody>
{#                                {% for categorie in categories|filter(categorie => not categorie.deleted)  %}#}
{#                                    <tr>#}
{#                                        <td><input type="checkbox" class="chkgrp" name="chkgrp[]" value="{{ categorie.id }}"></td>#}
{#                                        <td>{{ categorie.libelle }}</td>#}
{#                                        <td>{%  if categorie.categorieParente %} {{ categorie.categorieParente.libelle }} {% endif %}</td>#}
{#                                        <td><a class="btn btn-primary" href="{{ path('app_admin_edit_categorie',{"id":categorie.id}) }}"><i class="fa fa-edit"></i></a></td>#}
{#                                        <td>#}
{#                                            {%  if categorie.valid %}#}
{#                                                <a class="btn btn-success activate-link" href="{{ path('app_admin_changevalidite_categorie', {'id': categorie.id}) }}"> <i class="fa fa-check"></i></a>#}
{#                                            {% else %}#}
{#                                                <a class="btn btn-warning activate-link" href="{{ path('app_admin_changevalidite_categorie', {'id': categorie.id}) }}"> <i class="fa fa-times"></i></a>#}
{#                                            {% endif %}#}
{#                                        </td>#}
{#                                        <td><a href="{{ path('app_admin_delete_categorie', {'id': categorie.id}) }}" class="btn btn-danger disable-btn del-link" type="submit" ><i class="fa fa-trash"></i></a></td>#}
{#                                    </tr>#}
{#                                {% endfor %}#}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/association/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Association{% endblock %}

{% block body %}
    <h1>Create new Association</h1>

    {{ include('association/_form.html.twig') }}

    <a href="{{ path('association_index') }}">back to list</a>
{% endblock %}

templates/association/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association{% endblock %}

{% block body %}
    <h1>Association</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ association.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ association.titre }}</td>
            </tr>
            <tr>
                <th>Siege</th>
                <td>{{ association.siege }}</td>
            </tr>
            <tr>
                <th>But</th>
                <td>{{ association.but }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ association.logo }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ association.adresse }}</td>
            </tr>
            <tr>
                <th>NombreMembre</th>
                <td>{{ association.nombreMembre }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('association_index') }}">back to list</a>

    <a href="{{ path('association_edit', {'id': association.id}) }}">edit</a>

    {{ include('association/_delete_form.html.twig') }}
{% endblock %}